all::
	${MAKE} -C src

pkgprep:: all
	${MAKE} -C src $@
	${MAKE} -C include $@

clean::
	${MAKE} -C src $@

distclean::
	${MAKE} -C src $@
	${MAKE} -C include $@

pkgprep-clean::
	${MAKE} -C src $@
	${MAKE} -C include $@

